version: '3'
services:
  backend:
    build: ./backend
    container_name: blockchain-backend
    ports:
      - "3000:3000"
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: blockchain-frontend
    ports:
      - "8080:80"
    restart: on-failure

  db:
    image: mongo
    container_name: blockchain-db
    ports:
      - "27017:27017"
    restart: on-failure
